# 1. Credenciais do Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/db_laboratorio
spring.datasource.username=banco
spring.datasource.password=senhabanco
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do Hibernate (JPA)
# Mostra o SQL sendo executado no console (Ótimo para estudos)
spring.jpa.show-sql=true 

# ? CUIDADO - MODO LABORATÓRIO ?
# O Hibernate vai ler a classe Produto e criar a tabela tb_produtos sozinho no banco.
# Na Fase 2 nós usaremos 'validate' e deixaremos o Flyway criar a tabela.
spring.jpa.hibernate.ddl-auto=update